apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    spec:
      replicas: 3
      containers:
      - name: podinfod
        env:
          - name: PODINFO_UI_COLOR
            value: "#326ce5"