---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: jsellis
spec:
  serviceAccountName: flux-reconciler
  interval: 10m
  targetNamespace: jsellis
  chart:
    spec:
      chart: podinfo
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: podinfo
  values:
    # Default values for podinfo.
    replicaCount: 1
    logLevel: info
    ui:
      color: "#34577c"
      message: "This Helm Release is done with Flux"
      logo: ""

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: podinfo.jsellis.staging.nhbdemo.nl
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
       - secretName: podinfo-tls
         hosts:
           - podinfo.jsellis.staging.nhbdemo.nl